### ISSUE TITLE
Loop through directories

### ISSUE THREAD

**Issue by alex-oneill** [alex-oneill/OSScanning-Argparse_and_Logging#3]

**Comment by neowalter** [comment]
`
import argparse
import logging
import os
import shutil
import string

# delete 'filename = path' to show the log in the console and not save to a file
logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(levelname)s - %(threadName)s - %(message)s',
                    datefmt='%m-%d %H:%M',
                    )


def sizeConvert(size):                                   # change unit
    K, M, G = 1024, 1024**2, 1024**3
    if size >= G:
        size = format(size/G,'.4f')
        return str(size)+' G Bytes'
    elif size >= M:
        size = format(size/M, '.4f')
        return str(size)+' M Bytes'
    elif size >= K:
        size = format(size/K, '.4f')
        return str(size)+' K Bytes'
    else:
        return str(size)+' Bytes'


def list_drives():
    drive = string.ascii_uppercase
    for each_drive in drive:
        if os.path.exists(each_drive + ":\\"):
            path = each_drive + ":\\"
            print('-' * 50)
            print('In Drive', path)
            # logging.info('In Drive '.format(path))
            usage = shutil.disk_usage(path)
            print('Drives total size:', sizeConvert(usage.total))
            print('Drives used size:', sizeConvert(usage.used))
            print('Drives free size:', sizeConvert(usage.free))

            dirnum = 0
            filenum = 0

            for lists in os.listdir(path):
                sub_path = os.path.join(path, lists)
                # print(sub_path)
                if os.path.isfile(sub_path):
                    filenum = filenum + 1
                elif os.path.isdir(sub_path):
                    dirnum = dirnum + 1
            print('The total number of directories is:', dirnum)
            print('The total number of files is:', filenum)

list_drives()
`

**Comment by alex-oneill** [comment]
1.  Any idea how this would work for Mac? Even if we find a solution, I'm not sure if any of us use Mac to even test.

2.  When printing the info for a drive, right now we have folders/files in the first level of that drive, but do we need to recursively go through every sub-directory until we hit the bottom? That might be excessive and not really useful (C:\ = a huge number of files), but the actual project details aren't entirely clear.
